<a href="https://colab.research.google.com/github/IO-2024/IOTs_with_python/blob/main/Ch7.%20%EC%A7%80%EC%97%AD%20%EA%B0%84%20%EC%82%B0%EC%97%85%EC%97%B0%EA%B4%80%ED%9A%A8%EA%B3%BC%20%EB%B6%84%EC%84%9D_new_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [11]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [12]:
Rgt = "https://raw.githubusercontent.com/IO-2024/IOTs_with_python/main/data/Regional_IO_3regions_3sectors.csv"  # 지역 간 산업연관표(3지역, 3부문) 불러오기
Rgt_3 = pd.read_csv(Rgt)
Rgt_3.head()

rg  com  수도권 수도권.1 수도권.2  동부권 동부권.1 동부권.2  서부권 서부권.1  ... 동부권.3 동부권.4  \
0   rg  com  농산품   공산품   서비스  농산품   공산품   서비스  농산품   공산품  ...    소비    투자   
1  수도권  농산품    0     3     1    0     0     0    0     1  ...     0     0   
2  수도권  공산품    2   112    71    1    36    14    1    37  ...     9     6   
3  수도권  서비스    1    79   302    1    27    31    1    28  ...    33    13   
4  동부권  농산품    0     1     2    1     7     2    0     2  ...     3     1   

  동부권.5 서부권.3 서부권.4 서부권.5  지역최종수요계  지역총수요계    수입  총산출액  
0    수출    소비    투자    수출  제품최종수요계  제품총수요계  (공제)  총산출액  
1     0     0     0     0        1       6     0     6  
2     0     7     8     0      295     582     0   582  
3     0    31    11     0      706    1204     0  1204  
4     0     1     0     0        8      23     0    23  

[5 rows x 25 columns]

In [13]:
Rgt_empt = "https://raw.githubusercontent.com/IO-2024/IOTs_with_python/main/data/Regional_IO_3sector_3rg_emp.csv"  # 지역별 고용표(3지역, 3부문) 불러오기
Rgt_emp_3 = pd.read_csv(Rgt_empt)
Rgt_emp_3.head()

cd 수도권        동부권        서부권
농산품    135543.0   485642.0   606337.0
공산품   1818636.0  1444100.0   834780.0
서비스  10302991.0  4744657.0  3749541.0

## 지역, 산업구조 분석

In [15]:
Rgt_33 = Rgt_3.to_numpy()
Mt = Rgt_33[1:,2:].astype(float)
Mt

array([[   0.,    3.,    1.,    0.,    0.,    0.,    0.,    1.,    0.,
           5.,    1.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    1.,    6.,    0.,    6.],
       [   2.,  112.,   71.,    1.,   36.,   14.,    1.,   37.,   13.,
         287.,   29.,   21.,  215.,    9.,    6.,    0.,    7.,    8.,
           0.,  295.,  582.,    0.,  582.],
       [   1.,   79.,  302.,    1.,   27.,   31.,    1.,   28.,   28.,
         498.,  387.,  164.,   67.,   33.,   13.,    0.,   31.,   11.,
           0.,  706., 1204.,    0., 1204.],
       [   0.,    1.,    2.,    1.,    7.,    2.,    0.,    2.,    0.,
          15.,    3.,    0.,    0.,    3.,    1.,    0.,    1.,    0.,
           0.,    8.,   23.,    0.,   23.],
       [   0.,   43.,   38.,    4.,  158.,   40.,    1.,   36.,   13.,
         333.,   20.,   15.,    0.,   19.,   11.,  226.,    7.,    7.,
           0.,  305.,  638.,    0.,  638.],
       [   0.,    4.,   15.,    2.,   59.,   76.,    0.,    3.,    4.,

In [8]:
Va = Mt[-2,:10].reshape([1,10]) # 지역별, 부문별 부가가치 벡터
Ct = Mt[-1,:10].reshape([1,10])  # 지역별, 부문별 총산출액 벡터
Ct

array([[   6.,  582., 1204.,   23.,  638.,  479.,   29.,  491.,  379.,
        3831.]])

In [ ]:
# 지역기준
Sudo = np.vstack((Va[:,:3].sum(),Ct[:,:3].sum()))      # 수도권
Dongbu = np.vstack((Va[:,3:6].sum(),Ct[:,3:6].sum()))  # 동부권
Seobu = np.vstack((Va[:,6:9].sum(),Ct[:,6:9].sum()))   # 서부권

Sm_vact = np.vstack((Va[:,9],Ct[:,9]))
Vact_all = np.hstack((Sudo, Dongbu, Seobu, Sm_vact))

Va_sm = np.hstack((Sudo, Dongbu, Seobu))
Ctva_wgt = (Vact_all/Sm_vact)
Str_rg = np.vstack((Vact_all,Ctva_wgt))
Str_rg.round(1)

array([[ 831. ,  447. ,  359. , 1637. ],
       [1792. , 1140. ,  899. , 3831. ],
       [   0.5,    0.3,    0.2,    1. ],
       [   0.5,    0.3,    0.2,    1. ]])

### 지역별 산업 비중

In [ ]:
# 지역별 산업비중(총산출액 기준)
Sudo_ind_by_ct = (Mt[-1,:3]/Str_rg[1,0]*100) # 수도권
Dongbu_ind_by_ct = (Mt[-1,3:6]/Str_rg[1,1]*100) # 동부권
Seobu_ind_by_ct = (Mt[-1,6:9]/Str_rg[1,2]*100) # 동부권
Tot_ind_by_ct =  ((Mt[-1,:3]+Mt[-1,3:6]+Mt[-1,6:9])/Vact_all[1,3]*100)  # 전지역

Wgt_ind_by_region_ct = np.vstack((Sudo_ind_by_ct,Dongbu_ind_by_ct,Seobu_ind_by_ct, Tot_ind_by_ct))
print('지역별 산업 비중(총산출액 기준)  \n',Wgt_ind_by_region_ct.round(1))


지역별 산업 비중(총산출액 기준)  
 [[ 0.3 32.5 67.2]
 [ 2.  56.  42. ]
 [ 3.2 54.6 42.2]
 [ 1.5 44.7 53.8]]


In [ ]:
# 지역별 산업비중(부가가치 기준)

Sudo_ind_by_va = (Mt[-2,:3]/Str_rg[0,0]*100) # 수도권
Dongbu_ind_by_va = (Mt[-2,3:6]/Str_rg[0,1]*100) # 동부권
Seobu_ind_by_va = (Mt[-2,6:9]/Str_rg[0,2]*100) # 서부권
Tot_ind_by_va =  ((Mt[-2,:3]+Mt[-2,3:6]+Mt[-2,6:9])/Vact_all[0,3]*100)  # 전지역

Wgt_ind_by_region_va = np.vstack((Sudo_ind_by_va,Dongbu_ind_by_va,Seobu_ind_by_va,Tot_ind_by_va))
print('지역별 산업 비중(부가가치 기준)  \n',Wgt_ind_by_region_va.round(1))

지역별 산업 비중(부가가치 기준)  
 [[ 0.4 21.5 78.1]
 [ 2.9 37.6 59.5]
 [ 4.5 38.2 57.4]
 [ 2.  29.6 68.5]]


In [ ]:
CT_Reg = pd.DataFrame(Wgt_ind_by_region_ct.round(1), columns = ['농산품', '공산품', '서비스'],
                     index=['수도권', '동부권', '서부권','전지역']) # 변수명 붙여서 pandas로 내보내기
CT_Reg

농산품   공산품   서비스
수도권  0.3  32.5  67.2
동부권  2.0  56.0  42.0
서부권  3.2  54.6  42.2
전지역  1.5  44.7  53.8

In [ ]:
VA_Reg = pd.DataFrame(Wgt_ind_by_region_va.round(1), columns = ['수도권', '동부권', '서부권'],
                     index=['수도권', '동부권', '서부권','전지역']) # 변수명 붙여서 pandas로 내보내기
VA_Reg

수도권   동부권   서부권
수도권  0.4  21.5  78.1
동부권  2.9  37.6  59.5
서부권  4.5  38.2  57.4
전지역  2.0  29.6  68.5

### 지역별 산업 입지계수

In [ ]:
X_ij = Mt[-1,:9].reshape([1,9])
X = X_ij.sum()

In [ ]:
X_sudo =X_ij[-1,:3].sum().reshape([1,1]) # 수도권 총산출액
X_seobu =X_ij[-1,3:6].sum().reshape([1,1]) # 동부권 총산출액
X_dongbu =X_ij[-1,6:9].sum().reshape([1,1]) # 서부권 총산출액
print(X_sudo,X_seobu,X_dongbu)

[[1792.]] [[1140.]] [[899.]]


In [ ]:
X_agr=X_ij[-1,0]+X_ij[-1,3]+X_ij[-1,6] # 전국 농산품 총산출액
X_manu=X_ij[-1,1]+X_ij[-1,4]+X_ij[-1,7] # 전국 공산품 총산출액
X_serv=X_ij[-1,2]+X_ij[-1,5]+X_ij[-1,8] # 전국 서비스 총산출액
print(X_agr,X_manu, X_serv)

58.0 1711.0 2062.0


In [ ]:
X_i = np.concatenate((np.tile(X_sudo,3),np.tile(X_seobu,3),np.tile(X_dongbu,3)),axis=1)  # 지역별 산출액 합

In [ ]:
X_j = np.concatenate((X_agr.reshape([1,1]),X_manu.reshape([1,1]),X_serv.reshape([1,1])),axis=1) # 전국 농산품, 공산품, 서비스 산출액
X_j

array([[  58., 1711., 2062.]])

In [ ]:
X_ij_div_by_Xi=X_ij/X_i
X_ij_div_by_Xi

array([[0.003, 0.325, 0.672, 0.02 , 0.56 , 0.42 , 0.032, 0.546, 0.422]])

In [ ]:
Xj_div_by_X = np.tile(X_j/X,3).reshape(1,9)
Xj_div_by_X

array([[0.015, 0.447, 0.538, 0.015, 0.447, 0.538, 0.015, 0.447, 0.538]])

In [ ]:
LQ = (X_ij_div_by_Xi/Xj_div_by_X).reshape([1,9]).round(3)
LQ_f = np.vstack((LQ[:,:3],LQ[:,3:6],LQ[:,6:9])) #  지역별 산업별 비중
print('지역별 산업 입지계수 \n', LQ_f)

지역별 산업 입지계수 
 [[0.221 0.727 1.248]
 [1.333 1.253 0.781]
 [2.131 1.223 0.783]]


### 산업별 지역 비중 구하기

In [ ]:
# 산업기준

# 지역별 산출액 벡터
Arg_ct = np.hstack((Ct[:,0],Ct[:,3],Ct[:,6]))    # 농산품
Manu_ct = np.hstack((Ct[:,1],Ct[:,4],Ct[:,7]))  # 공산품
Serv_ct = np.hstack((Ct[:,2],Ct[:,5],Ct[:,8]))  # 서비스

# 지역별 부가가치 벡터
Arg_va = np.hstack((Va[:,0],Va[:,3],Va[:,6]))    # 농산품
Manu_va = np.hstack((Va[:,1],Va[:,4],Va[:,7]))  # 공산품
Serv_va= np.hstack((Va[:,2],Va[:,5],Va[:,8]))  # 서비스

In [ ]:
Arg_ct_sm = np.sum(Arg_ct)
Manu_ct_sm = np.sum(Manu_ct)
Serv_ct_sm = np.sum(Serv_ct)

Arg_va_sm = np.sum(Arg_va)
Manu_va_sm = np.sum(Manu_va)
Serv_va_sm = np.sum(Serv_va)

In [ ]:
# 산업별 지역 비중(총산출액 기준)
Arg_ct_wgt = (Arg_ct/Arg_ct_sm)  # 농산품
Manu_ct_wgt = (Manu_ct/Manu_ct_sm)  # 공산품
Serv_ct_wgt = (Serv_ct/Serv_ct_sm)  # 서비스
Serv_ct_wgt

In [ ]:
# 산업별 지역 비중(부가가치 기준)
Arg_va_wgt = (Arg_va/Arg_va_sm)  # 농산품
Manu_va_wgt = (Manu_va/Manu_va_sm)  # 공산품
Serv_va_wgt = (Serv_va/Serv_va_sm)  # 서비스
Serv_va_wgt

In [ ]:
Ct_by_ind = np.vstack((Arg_ct_wgt, Manu_ct_wgt, Serv_ct_wgt))
Va_by_ind = np.vstack((Arg_va_wgt, Manu_va_wgt, Serv_va_wgt))
print('산업별 지역 비중(총산출액 기준) \n',(Ct_by_ind*100).round(1), '\n')
print('산업별 지역 비중(부가가치 기준) \n', (Va_by_ind*100).round(1))

In [ ]:
CT_IND = pd.DataFrame((Ct_by_ind*100).round(1), columns = ['수도권', '동부권', '서부권'],
                     index=['농산품', '공산품', '서비스']) # 변수명 붙여서 pandas로 내보내기
CT_IND

In [ ]:
VA_IND = pd.DataFrame((Va_by_ind*100).round(1), columns = ['수도권', '동부권', '서부권'],
                     index=['농산품', '공산품', '서비스']) # 변수명 붙여서 pandas로 내보내기
VA_IND

In [ ]:
# csv 파일로 내보내기
VA_IND.to_csv('부가가치_산업별_지역별_비중.csv', encoding='utf_8-sig')
CT_IND.to_csv('산출액_산업별_지역별_비중.csv', encoding='utf_8-sig')

### 산업별 집중계수

In [ ]:
Wgt_rg = Str_rg[-1,:3].reshape([1,3])   # str_rg는 지역별 총산출액 및 총부가가치의 금액과 비중(수도권, 동부권, 서부권)
Wgt_rg

In [ ]:
Arg_concst = (abs(Wgt_rg[:,0]-Ct_by_ind[0,0])+abs(Wgt_rg[:,1]-Ct_by_ind[0,1])+abs(Wgt_rg[:,2]-Ct_by_ind[0,2]))/2  # 농산품
Manu_concst = (abs(Wgt_rg[:,0]-Ct_by_ind[1,0])+abs(Wgt_rg[:,1]-Ct_by_ind[1,1])+abs(Wgt_rg[:,2]-Ct_by_ind[1,2]))/2  # 공산품
Serv_concst = (abs(Wgt_rg[:,0]-Ct_by_ind[2,0])+abs(Wgt_rg[:,1]-Ct_by_ind[2,1])+abs(Wgt_rg[:,2]-Ct_by_ind[2,2]))/2  # 서비스

In [ ]:
All_concst = np.vstack((Arg_concst, Manu_concst, Serv_concst))  # 집중계수
print('산업별 집중계수 \n', All_concst.round(3))

In [ ]:
All_concst_df = pd.DataFrame(All_concst.round(3), columns = ['집중계수'],
                     index=['농산품', '공산품', '서비스']) # 변수명 붙여서 pandas로 내보내기
All_concst_df

### 지역별 투입구조

In [ ]:
Dm_1 = Mt[0:9,0:9].astype(float)
Im_1 = Mt[9:12,0:9].astype(float)

In [ ]:
import scipy.linalg as linalg

In [ ]:
Mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
Mtx_for_inter=np.where(Mtx_for_int == 1, 0, 1)

In [ ]:
Intra_input = Mtx_for_int*Dm_1  # 지역별 자기지역 생산품 투입액

In [ ]:
Inter_input = Mtx_for_inter*Dm_1  # 지역별 타지역 생산품 투입액

In [ ]:
Intra_rg_sm = Intra_input.sum(axis=0) # 지역별 부문별 자기지역 생산품 투입액계
Inter_rg_sm = Inter_input.sum(axis=0) # 지역별 부문별 타지역 생산품 투입액계
Imps_input =Im_1.sum(axis=0)  # 지역별 부문별 수입중간투입계
print(Intra_rg_sm)

In [ ]:
print(Intra_rg_sm, '\n')
print(Inter_rg_sm, '\n')
print(Imps_input)

In [ ]:
Code = np.array([[1,1,1,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 3x33 매트릭스
       [0,0,0,1,1,1,0,0,0],
       [0,0,0,0,0,0,1,1,1]])
Code.T

In [ ]:
Intra_tot = (Intra_rg_sm@Code.T).T  # 지역별 자기지역 생산품 투입액계
Inter_tot = (Inter_rg_sm@Code.T).T  # 지역별 타지역 생산품 투입액계
Imps_tot =  (Imps_input@Code.T).T  # 지역별 수입중간투입계
Intra_tot

In [ ]:
Input_dom = Intra_tot + Inter_tot
Input_all = Input_dom + Imps_tot

Input_tot = np.vstack((Intra_tot, Inter_tot, Input_dom,Imps_tot, Input_all)).T
# input_tot_f = np.hstack((input_tot,input_tot.sum(axis=0).reshape([1,5])))
Input_tot.ndim

In [ ]:
Input_nation = Input_tot.sum(axis=0).reshape([1,5])
Input_nation.ndim

In [ ]:
Input_tem = np.vstack((Input_tot, Input_nation))
Input_fin = np.hstack((Input_tem,Str_rg[0,:].reshape([4,1])))
Input_fin

In [ ]:
Ct_rg = Str_rg[1,:]
Ct_rg_m = np.tile(Ct_rg, reps=[6,1]).T
Ct_rg_m

In [ ]:
Input_tot_wgt = Input_fin/Ct_rg_m
print('지역별 투입구조 \n', (Input_tot_wgt*100).round(1))

In [ ]:
Input_df = pd.DataFrame((Input_tot_wgt*100).round(1), columns = ['자기지역생산품','타지역생산품','국산품','수입품','중간투입계','부가가치'],
                     index=['수도권', '동부권', '서부권', '전지역']) # 변수명 붙여서 pandas로 내보내기
Input_df

In [ ]:
Input_df.to_csv('지역별 투입구조.csv', encoding='utf_8-sig')

## 지역별 배분구조

In [ ]:
Intra_tot

In [ ]:
Intra_itd_dstr = Intra_input.sum(axis=1)   # 지역별 부문별 자기지역 생산품 중간수요계
Inter_itd_dstr = Inter_input.sum(axis=1)   # 지역별 부문별 타지역 생산품 중간수요계
Itd_dstr_sm = Intra_itd_dstr + Inter_itd_dstr
Itd_dstr_sm

In [ ]:
Intra_itd_tot = (Intra_itd_dstr@Code.T)  # 지역별 부문별 자기지역 최종수요계
Inter_itd_tot = (Inter_itd_dstr@Code.T)  # 지역별 부문별 타지역 최종수요계
Itd_dstr_tot = (Itd_dstr_sm@Code.T)  # 지역별 중간수요계
Itd_dstr_tot

In [ ]:
Int_dstr = np.vstack((Intra_itd_tot, Inter_itd_tot, Itd_dstr_tot)).T # 지역별 자기지역 중간수요, 타지역 중간수요, 중간수요계

In [ ]:
Exp_sudo = Mt[:9,12].sum() # 지역별 총수출액(수도권)
Exp_dongbu = Mt[:9,15].sum() # 지역별 총수출액(동부권)
Exp_seobu = Mt[:9,18].sum() # 지역별 총수출액(서부권)

In [ ]:
Exp_tot = np.hstack((Exp_sudo, Exp_dongbu, Exp_seobu))

In [ ]:
print('지역별 자기지역 중간수요, 타지역 중간수요, 중간수요계','\n', Int_dstr, '\n')
print('지역별 총수출액', '\n', Exp_tot)

In [ ]:
Mt_for_nonex = Mt
Fd_rg = Mt_for_nonex[:9,10:19] # 지역별 부문별 최종수요 벡터
Fd_rg[:,2] = 0            #수출을 0으로 만든 최종수요매트릭스 만들기(수출은 자기지역 또는 타지역에 포함되지 않음)
Fd_rg[:,5] = 0            #수출을 0으로 만든 최종수요매트릭스 만들기(수출은 자기지역 또는 타지역에 포함되지 않음)
Fd_rg[:,8] = 0            #수출을 0으로 만든 최종수요매트릭스 만들기(수출은 자기지역 또는 타지역에 포함되지 않음)
Fd_rg

In [ ]:
Intra_fd = (Mtx_for_int*Fd_rg).sum(axis=1) # 지역별 부문별 자기지역 국내 최종수요계
Intra_fd

In [ ]:
Inter_fd =  (Mtx_for_inter*Fd_rg).sum(axis=1) # # 지역별 부문별 타지역 국내 최종수요계

In [ ]:
Tot_fd = Intra_fd + Inter_fd # 최종수요계

In [ ]:
Intra_fd_tot = (Intra_fd@Code.T)  # 자기지역 최종종요 비중(전체산업)
Inter_fd_tot = (Inter_fd@Code.T)  # 타지역 최종종요 비중(전체산업)
Tot_fd_tot = (Tot_fd@Code.T)

In [ ]:
Fd_dstr = np.vstack((Intra_fd_tot, Inter_fd_tot, Tot_fd_tot)).T

In [ ]:
Total_dstr = np.hstack((Int_dstr, Fd_dstr, Exp_tot.reshape([3,1])))
Total_dstr

In [ ]:
Tot_dstr_ct = Total_dstr[:,2]+Total_dstr[:,5]+Total_dstr[:,6]
Tot_dstr_ct

In [ ]:
Tot_dstr_col_sm = np.hstack((Total_dstr,Tot_dstr_ct.reshape([3,1])))
Tot_dstr_col_sm

In [ ]:
Tot_dstr_rw_sm = Tot_dstr_col_sm.sum(axis=0)
Tot_dstr_rw_sm

In [ ]:
Tot_dstr = np.vstack((Tot_dstr_col_sm, Tot_dstr_rw_sm))
Tot_dstr

In [ ]:
Sm_col = np.tile(Tot_dstr[:,7].reshape([4,1]), reps=[1,8])
Sm_col

In [ ]:
Tot_dstr_ratio = Tot_dstr/Sm_col
print('지역별 배분구조', '\n', (Tot_dstr_ratio*100).round(1))

In [ ]:
dstr_df = pd.DataFrame((Tot_dstr_ratio*100).round(1), columns = [['중간재', '중간재', '중간재', '최종수요', '최종수요', '최종수요','수출', '합계'],
                                     ['자기지역', '타지역', '소계', '자기지역', '타지역', '소계','수출', '합계' ]],
                       index = ['수도권', '동부권', '서부권', '전지역'])
dstr_df

In [ ]:
dstr_df.to_csv('지역별 배분구조.csv', encoding='utf_8-sig')

### 지역 이출입

In [ ]:
Tra_int = Mt[0:9,0:9] # 지역별 부문별 중간투입(수요)
Tra_int

In [ ]:
Tra_fd = Fd_rg  # 지역별 부문별 최종수요
Tra_fd

In [ ]:
Tot_tra = (Tra_int+Tra_fd).astype(float)  #지역별 산업별 이출입 매트릭스 9x9
Tot_tra

In [ ]:
Cd_for_tr = np.array([[1,1,1,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 6x6 매트릭스
       [0,0,0,1,1,1,0,0,0],
       [0,0,0,0,0,0,1,1,1]])


In [ ]:
Fnl_tra = (Cd_for_tr@Tot_tra)@Cd_for_tr.T # 지역별 매트릭스(자기지역 + 타지역)

In [ ]:
Fnl_tra_rw_sm = Fnl_tra.sum(axis=1).reshape([3,1])
Fnl_tra_rw_mtx = np.hstack((Fnl_tra,Fnl_tra_rw_sm))

Fnl_tra_col_sm = Fnl_tra_rw_mtx.sum(axis=0).reshape([1,4])

#지역 간 이출입 구조

Fnl_tra_ff = np.vstack((Fnl_tra_rw_mtx,Fnl_tra_col_sm)) # 지역간 이출입 구조
Fnl_tra_ratio = Fnl_tra_ff [:3,:]/(np.tile(Fnl_tra_ff[:3,3], reps=[4,1]).T)
print('지역 간 이출구조', '\n', (Fnl_tra_ratio*100).round(1))

In [ ]:
Fnl_inter_ratio = Fnl_tra_ff [:,:3]/(np.tile(Fnl_tra_ff[3,:3], reps=[4,1]))
print('지역 간 이입구조', '\n', (Fnl_inter_ratio*100).round(1))

In [ ]:
Tra_df = pd.DataFrame(Fnl_tra_ff, columns = ['수도권', '동부권', '서부권', '총이출'],
                                     index=['수도권', '동부권', '서부권', '총이입'])
Tra_df

In [ ]:
Tra_df.to_csv('지역간 이출입 구조.csv', encoding='utf_8-sig')

###..산업연관효과분석

In [ ]:
Dm_1 = Mt[0:9,0:9].astype(float)
Im_1 = Mt[9:12,0:9].astype(float)
# Dm_1 = Dt[0:4,1:10].astype(float)
# Im_1 = It[0:4,1:10].astype(float)
# print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1.astype(float))  # 수입거래표 확인

In [ ]:
Ct =Mt[-1,:9]  # 총산출액 벡터
Ct

In [ ]:
Ct_m = np.tile(Ct, reps=[9,1]) # 총산출액 벡터를 9번 행반복

In [ ]:
# At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad =(Dm_1/Ct_m)  # 국산투입계수

# print('총투입계수표 : \n', At)
# print('국산투입계수표 : \n', Ad)
#
# df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
print('국산투입계수', '\n', Ad.round(3))

In [ ]:
Ad_df = pd.DataFrame(Ad, columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Ad_df.index.names=['지역', '상품']
Ad_df

##### 생산유발계수(Lf)

In [ ]:
Lf = np.linalg.inv(np.identity(9)-Ad)    # 생산유발계수
Lf_sm_cl = np.hstack((Lf, Lf.sum(axis=1).reshape([9,1]))) # 생산유발계수의 열합
Lf_sm_rw = np.vstack((Lf_sm_cl,Lf_sm_cl.sum(axis=0))) # 생산유발계수의 행합
print('생산유발계수', '\n', Lf_sm_rw)

#### 수입유발계수(Li)

In [ ]:
Dig_imp = linalg.block_diag(Mt[9:12,0:3],Mt[9:12,3:6],Mt[9:12,6:9]) # 지역별 수입거래표의 대각행렬

In [ ]:
Ai = Dig_imp/Ct_m
Ai

In [ ]:
Li = Ai@Lf  #수입유발계수
Li.shape

Li_sm_cl = np.hstack((Li, Li.sum(axis=1).reshape([9,1]))) # 수입유발계수의 열합
Li_sm_rw = np.vstack((Li_sm_cl,Li_sm_cl.sum(axis=0))) # 수입유발계수의 행합
print('수입유발계수', '\n', Li_sm_rw.round(2))


#### 부가가치유발계수(Lv)

In [ ]:
Va_r = Mt[-2,:9]/Ct # 지역별 부문별 부가가치율
Va_r

In [ ]:
Va_m = np.diag(Va_r)  # 지역별 부문별 부가가치율의 대각행렬
Va_m

In [ ]:
Lv = Va_m@Lf  #부가가치유발계수
Lv_sm_cl = np.hstack((Lv, Lv.sum(axis=1).reshape([9,1]))) # 부가가치유발계수의 열합
Lv_sm_rw = np.vstack((Lv_sm_cl,Lv_sm_cl.sum(axis=0))) # 부가가치유발계수의 행합
print('부가가치유발계수', '\n', Lv_sm_rw.round(2))

In [ ]:
# df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

In [ ]:

Lf_df = pd.DataFrame(Lf.round(3), columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lf_df.index.names=['지역', '상품']
Lf_df  #pandas로 내보내기

In [ ]:
Lv_df = pd.DataFrame(Lv, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lv_df.index.names=['지역', '상품']
# Lv_df  #pandas로 내보내기

In [ ]:
Li_df = pd.DataFrame(Li, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Li_df.index.names=['지역', '상품']
# Li_df  #pandas로 내보내기

In [ ]:
Lf_df.to_csv('생산유발계수.csv', encoding='utf_8-sig')
Lv_df.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
Li_df.to_csv('수입유발계수.csv', encoding='utf_8-sig')

## 취업계수 및 취업유발계수

In [ ]:
Rgt_emp_3

In [ ]:
Emp_3 = Rgt_emp_3.to_numpy() # 지역별 부문별 취업자수
Emp = Emp_3[0:4,0:4].astype(float)
Emp

In [ ]:
Emp_row = np.concatenate((Emp[:,0],Emp[:,1],Emp[:,2]))
Emp_row.shape

In [ ]:
Ct.shape

In [ ]:
# emp_row = np.vstack(sudo_emp,dongbu_emp)

In [ ]:
Emp_ratio = ((Emp_row/Ct)/1000).T # 취업계수(십억원당)
Emp_ratio = Emp_ratio.reshape(1,9)
print('취업계수', '\n', Emp_ratio)

In [ ]:
Emp_Lf= np.diag(Emp_ratio.flatten())@Lf #취업유발계수
Emp_sm_cl = np.hstack((Emp_Lf, Emp_Lf.sum(axis=1).reshape([9,1]))) # 취업유발계수 열합
Emp_sm_rw = np.vstack((Emp_sm_cl,Emp_sm_cl.sum(axis=0))) # 취업유발계수 행합
print('취업유발계수', '\n', Emp_sm_rw.round(1))

In [ ]:
Emp_ratio_df = pd.DataFrame(Emp_ratio.round(3), columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['취업계수']])

Emp_Lf_df = pd.DataFrame(Emp_Lf, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Emp_Lf_df.index.names=['지역', '상품']

#pandas로 내보내기

In [ ]:
Emp_ratio_df

In [ ]:
Emp_Lf_df

In [ ]:
Emp_ratio_df.to_csv('지역별_상품별_취업계수.csv', encoding='utf_8-sig')
Emp_Lf_df.to_csv('지역별_상품별_취업유발계수.csv', encoding='utf_8-sig')

### Tiva_in and Tiva_out

## 수도권의 Tiva_in and Tiva_out

In [ ]:
# 수도권의 타지역에 대한 부가가치 이입 및 이출
Fd = Mt[:9,10:19]
Fd_sudo = Fd[:,0:3].sum(axis=1)
Fd_non_sudo = Fd[:,3:9].sum(axis=1)

In [ ]:
Mtx_for_vain = Lv@np.diagflat(Fd_sudo)
Mtx_for_vaout = Lv@np.diagflat(Fd_non_sudo)
Mtx_for_vaout

In [ ]:
Tiva_in_sudo = Mtx_for_vaout[:3,:] # 타지역 최종수요에 의한 수도권 부가가치유발액
Tiva_in_sudo_sm = Tiva_in_sudo.sum(axis=1).reshape([3,1])
Tiva_in_sudo_all = Tiva_in_sudo_sm.sum()
Tiva_in_sudo_vec = np.vstack((Tiva_in_sudo_sm,Tiva_in_sudo_all))

Tiva_out_sudo = Mtx_for_vain[3:,:] # 수도권 최종수요에 의한 타지역 부가가치유발액
Tiva_out_sudo_sm = Tiva_out_sudo.sum(axis=1).reshape([6,1])
Tiva_out_sudo_arg = Tiva_out_sudo_sm[0,:] + Tiva_out_sudo_sm[3, :]
Tiva_out_sudo_manu = Tiva_out_sudo_sm[1,:] + Tiva_out_sudo_sm[4, :]
Tiva_out_sudo_serv = Tiva_out_sudo_sm[2,:] + Tiva_out_sudo_sm[5, :]
Tiva_out_sudo_all = Tiva_out_sudo_sm.sum()
Tiva_out_sudo_vec = np.vstack((Tiva_out_sudo_arg,Tiva_out_sudo_manu,Tiva_out_sudo_serv,Tiva_out_sudo_all))

In [ ]:
Tiva_mt=np.hstack((Tiva_in_sudo_vec, Tiva_out_sudo_vec, (Tiva_in_sudo_vec-Tiva_out_sudo_vec) ))
print('수도권의 타지역에 대한 부가가치 이입 및 이출', '\n' ,Tiva_mt.round(0))

In [ ]:
Tiva_in_sudo_df = pd.DataFrame(Tiva_in_sudo.round(3), columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권'],
                                           ['농산품', '공산품', '서비스']])

Tiva_out_sudo_df = pd.DataFrame(Tiva_out_sudo, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스','농산품', '공산품', '서비스']])

Tiva_in_sudo_df.index.names=['지역', '상품']
Tiva_out_sudo_df.index.names=['지역', '상품']
Tiva_out_sudo_df

In [ ]:
Tiva_in_sudo_df.to_csv('부가가치이입.csv', encoding='utf_8-sig')
Tiva_out_sudo_df.to_csv('부가가치이출.csv', encoding='utf_8-sig')