<a href="https://colab.research.google.com/github/IO-2024/IOTs_with_python/blob/main/Ch_%EB%B6%80%EB%A1%9D_2.%20%EB%B6%80%EB%AC%B8%ED%86%B5%ED%95%A9_ICIO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [99]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [100]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [101]:
# from google.colab import drive
# drive.mount('/content/drive')

In [102]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

[ICIO_다운로드 사이트](https://www.oecd.org/sti/ind/inter-country-input-output-tables.htm)

In [103]:
Icio = pd.read_csv('/content/2020.csv', low_memory = False)  # ICIO 불러오기

In [104]:
Icio_1 = Icio.to_numpy()
Icio_2=Icio_1[:,1:]
Icio_2.shape

(3648, 4108)

### 한국 1, 중국 2, 미국 3, ROW 4

In [105]:
url_cdd = "https://raw.githubusercontent.com/IO-2024/IOTs_with_python/main/data/cd_icio_f_new.csv"  #코드매치 파일 불러오기
Cd = pd.read_csv(url_cdd)
Cd.head()

cons  old  new
0  ARG_A01_02    1   10
1     ARG_A03    2   10
2  ARG_B05_06    3   11
3  ARG_B07_08    4   11
4     ARG_B09    5   11

In [106]:
Ccdd = Cd.to_numpy()
Cd_for_itr = Ccdd[:,1:]
Cd_for_itr

array([[1, 10],
       [2, 10],
       [3, 11],
       ...,
       [3643, 6],
       [3644, 6],
       [3645, 6]], dtype=object)

In [107]:
Mtx = np.zeros((12,3645)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
Cd_3 = Cd_for_itr[:,1]
Cd_33 = Cd_for_itr[:,0]
row=Cd_3
col=Cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [108]:
Code=Mtx.reshape([12,3645])
Code.shape

(12, 3645)

In [109]:
Nae_tot = (Code@Icio_2[0:3645,0:3645])@Code.T # 중간투입(수요) 12x12 만들기
Nae_tot.shape

(12, 12)

In [110]:
# url_cdtx = "https://raw.githubusercontent.com/Muraka64/IOTs_with_python/main/data/cd_tax_new.csv"  # 세금 코드매치 파일 불러오기
# Cd_tx = pd.read_csv(url_cdtx)
# Cd_tx.shape

In [111]:
url_cns = "https://raw.githubusercontent.com/IO-2024/IOTs_with_python/main/data/cd_cons_new.csv"  # 국가 코드매치 파일 불러오기
Cd_cns = pd.read_csv(url_cns)
Cd_cns.shape

(77, 3)

In [112]:
Ccdd_cns = Cd_cns.to_numpy()
Cd_for_itr_cns = Ccdd_cns[:,1:]
# cd_for_itr_tx

In [113]:
Mtx_cns= np.zeros((4,77)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
Cd_3 = Cd_for_itr_cns[:,1]
Cd_33 = Cd_for_itr_cns[:,0]
Row=Cd_3
Col=Cd_33
for i, j in zip(Row,Col):
  Mtx_cns[i-1,j-1] = 1
print(Mtx_cns)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]]


In [114]:
# code_tx = Mtx_tx
Code_cns = Mtx_cns
Code_cns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.

In [115]:
Nae_tx = Icio_2[3645,0:3645]@Code.T # 세금 행을 12부문으로 만들기


In [116]:
Vact_row = Icio_2[-2:,0:3645]@Code.T # 부가가치 및 산출액
Vact_row.shape

(2, 12)

In [117]:
url_cdfd = "https://raw.githubusercontent.com/IO-2024/IOTs_with_python/main/data/cd_fd_4cons_new.csv"  #최종수요 코드매치 파일 불러오기
Cd_fd = pd.read_csv(url_cdfd)
Cd_fd.shape

(462, 3)

In [118]:
Ccdd_fd = Cd_fd.to_numpy()
Cd_for_itr_fd = Ccdd_fd[:,1:3]
Cd_for_itr_fd.shape

(462, 2)

In [119]:
Cd_33.shape

(77,)

In [120]:
Mtx_fd= np.zeros((4,462)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
Cd_3 = Cd_for_itr_fd[:,1]
Cd_33 = Cd_for_itr_fd[:,0]
Row=Cd_3
Col=Cd_33
for i, j in zip(Row,Col):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 1. 1.]]


In [121]:
Code_fd = Mtx_fd
Code_fd.shape

(4, 462)

In [122]:
Fd = Code@Icio_2[0:3645,3645:4107]@Code_fd.T # 최종수요를 12부문으로 만들기
Code_fd.shape

(4, 462)

In [123]:
Icio_2[0:3645,3645:4107].sum()

81796440.98814319

In [124]:
Fd_tx = Icio_2[3645,3645:4107]@Code_fd.T
Fd_tx

array([73671.86296299999, 487852.95911000005, 522672.210866,
       2476992.3649929976], dtype=object)

In [125]:
Fd.shape

(12, 4)

In [126]:
Fd_row=np.concatenate((Fd,Fd_tx.reshape([1,4]),np.zeros((2,4))))
Fd_row.sum()

85357630.38611801

In [127]:
Icio_row = np.concatenate((Nae_tot,Nae_tx.reshape([1,12]), Vact_row))
Icio_row.shape

(15, 12)

In [128]:
Icio_col = np.concatenate((Icio_row, Fd_row), axis=1)

In [129]:
Icio_col_sm = Icio_col.sum(axis=1).reshape([15,1]) # 충수요계(산출액과 동일)
Icio_col_sm[-2:,:] = 0     # 총수요 열에서 부가가치,산출액 0으로 만들기

In [130]:
Icio_f = np.concatenate((Icio_col, Icio_col_sm), axis=1).astype(float)
Icio_f.shape

(15, 17)

In [131]:
ICIO_trl = (Icio_f/100).round(0) # 억달러
print('3부문_4개국_ICIO', '\n', ICIO_trl)

3부문_4개국_ICIO 
 [[    25.    247.     91.      0.      0.      0.      0.      3.      1.
       1.      3.      1.    143.      0.      1.      2.    518.]
 [   111.   5200.   2638.     59.   1097.    340.     10.    194.    177.
      67.   1120.    536.   1623.    278.    349.    890.  14690.]
 [    62.   2314.   5377.     19.    198.    147.      2.     29.     82.
      14.    203.    345.  11605.    105.     81.    263.  20846.]
 [     1.      6.      2.   4912.  10317.   1336.      6.     19.      4.
      33.    106.     21.      2.   5712.      6.     79.  22559.]
 [    10.    585.    235.   4625.  84294.  37897.     42.    882.   1179.
     270.   5551.   3633.    253.  28453.   1978.   6876. 176763.]
 [     2.     79.    116.   1885.  23537.  36089.      5.    112.    283.
      47.    780.   1494.     83. 101032.    351.   1507. 167403.]
 [     2.     15.      5.     59.    152.     17.    780.   1964.    151.
     100.    309.     49.      5.     40.    997.    192.   4836.

In [132]:
ICIO_df = pd.DataFrame(ICIO_trl, columns = [['한국', '한국', '한국', '중국', '중국', '중국', '미국', '미국', '미국', 'ROW', 'ROW', 'ROW','한국', '중국', '미국', 'ROW','총계'],

                                          ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '최종수요','최종수요','최종수요','최종수요', '총수요']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국', '미국', '미국', '미국', 'ROW', 'ROW', 'ROW','세금','부가가치','총투입계'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스','세금','부가가치','총투입계']])
ICIO_df.index.names=['국가', '산업']

In [133]:
ICIO_df

한국                         중국                          미국  \
             농산품      공산품      서비스      농산품       공산품       서비스     농산품   
국가   산업                                                                   
한국   농산품    25.0    247.0     91.0      0.0       0.0       0.0     0.0   
     공산품   111.0   5200.0   2638.0     59.0    1097.0     340.0    10.0   
     서비스    62.0   2314.0   5377.0     19.0     198.0     147.0     2.0   
중국   농산품     1.0      6.0      2.0   4912.0   10317.0    1336.0     6.0   
     공산품    10.0    585.0    235.0   4625.0   84294.0   37897.0    42.0   
     서비스     2.0     79.0    116.0   1885.0   23537.0   36089.0     5.0   
미국   농산품     2.0     15.0      5.0     59.0     152.0      17.0   780.0   
     공산품     5.0    166.0     90.0     36.0     458.0     172.0   728.0   
     서비스     4.0    115.0    144.0     50.0     368.0     272.0   770.0   
ROW  농산품     3.0     31.0     14.0    198.0     518.0      58.0   142.0   
     공산품    21.0   1384.0    577.0    391.0    9590.0    2504.0   214.0   
     서비스    10.0    346.0    444.0    225.0    2225.0    1686.0   113.0   
세금   세금      5.0    226.0    352.0    120.0    2861.0    2493.0    25.0   
부가가치 부가가치  256.0   3975.0  10762.0   9980.0   41148.0   84394.0  1998.0   
총투입계 총투입계  518.0  14690.0  20846.0  22559.0  176763.0  167403.0  4836.0   

                                  ROW                           한국        중국  \
               공산품       서비스      농산품       공산품       서비스     최종수요      최종수요   
국가   산업                                                                        
한국   농산품       3.0       1.0      1.0       3.0       1.0    143.0       0.0   
     공산품     194.0     177.0     67.0    1120.0     536.0   1623.0     278.0   
     서비스      29.0      82.0     14.0     203.0     345.0  11605.0     105.0   
중국   농산품      19.0       4.0     33.0     106.0      21.0      2.0    5712.0   
     공산품     882.0    1179.0    270.0    5551.0    3633.0    253.0   28453.0   
     서비스     112.0     283.0     47.0     780.0    1494.0     83.0  101032.0   
미국   농산품    1964.0     151.0    100.0     309.0      49.0      5.0      40.0   
     공산품   13286.0   12736.0    174.0    2690.0    1463.0     81.0     179.0   
     서비스   11902.0   93573.0    186.0    2134.0    4374.0     90.0     419.0   
ROW  농산품     473.0      94.0   6903.0   13976.0    3827.0     13.0     135.0   
     공산품    4385.0    3307.0   5434.0   94038.0   56690.0    393.0    1836.0   
     서비스    1374.0    3809.0   4520.0   52110.0  185443.0    296.0    1867.0   
세금   세금      680.0    1478.0    437.0    4178.0    8404.0    737.0    4879.0   
부가가치 부가가치  24291.0  177144.0  23285.0   88535.0  330938.0      0.0       0.0   
총투입계 총투입계  59593.0  294019.0  41470.0  265732.0  597219.0      0.0       0.0   

                 미국       ROW        총계  
               최종수요      최종수요       총수요  
국가   산업                                  
한국   농산품        1.0       2.0     518.0  
     공산품      349.0     890.0   14690.0  
     서비스       81.0     263.0   20846.0  
중국   농산품        6.0      79.0   22559.0  
     공산품     1978.0    6876.0  176763.0  
     서비스      351.0    1507.0  167403.0  
미국   농산품      997.0     192.0    4836.0  
     공산품    24792.0    2537.0   59593.0  
     서비스   175868.0    3751.0  294019.0  
ROW  농산품      147.0   14937.0   41470.0  
     공산품     6106.0   78861.0  265732.0  
     서비스     3605.0  339144.0  597219.0  
세금   세금      5227.0   24770.0   56872.0  
부가가치 부가가치       0.0       0.0       0.0  
총투입계 총투입계       0.0       0.0       0.0

In [134]:
ICIO_df.to_csv('ICIO_4cons_3secs_1Fd_2020.csv',encoding="utf-8-sig")